# Generated by Django 4.2.13 on 2024-06-08 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('option_a', models.CharField(max_length=100)),
                ('is_a_correct', models.BooleanField(default=False)),
                ('option_b', models.CharField(max_length=100)),
                ('is_b_correct', models.BooleanField(default=False)),
                ('option_c', models.CharField(max_length=100)),
                ('is_c_correct', models.BooleanField(default=False)),
                ('option_d', models.CharField(max_length=100)),
                ('is_d_correct', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quizzes.test')),
            ],
        ),
    ]
